'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Activity,BarChart3,BriefcaseBusiness,CalendarDays,CheckCircle2,ClipboardList,Clock,FileText,Home,Menu,Plus,Search,Settings,Target,TrendingUp,Users,Layers3,ListTodo,ChevronRight,X,AlertTriangle,LogOut} from 'lucide-react';
import {signOut} from 'next-auth/react';

type Data={clients:any[];team:any[];verticals:any[];proposals:any[];projects:any[];tasks:any[];dailyLabels:string[];summary:any;currentUser?:{id:string;name:string;role:'ADMIN'|'MEMBER'}};
const colors=['#2563eb','#10b981','#8b5cf6','#f59e0b','#ec4899','#06b6d4','#64748b','#f97316','#6366f1','#14b8a6'];
const nav=[['Overview',Home],['Clients',Users],['Projects',BriefcaseBusiness],['Verticals',Layers3],['Tasks',ListTodo],['Team',Users],['Proposals',FileText],['Reports',ClipboardList],['Settings',Settings]] as const;
export default function Dashboard(){
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [section,setSection]=useState('Overview'); const [selected,setSelected]=useState<string|null>(null); const [menu,setMenu]=useState(false); const [search,setSearch]=useState(''); const [showForm,setShowForm]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/dashboard');const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to load dashboard data.');setData(payload)}catch(error){setData(null);setError(error instanceof Error?error.message:'Unable to load dashboard data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading) return <div className="loading">Loading 31G Operations Center…</div>;
 if(error) return <div className="loading">{error}</div>;
 if(!data) return <div className="loading">No dashboard data available.</div>;
 const selectedMember=data.team.find(t=>t.id===selected);
 const filteredClients=data.clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase()));
 const filteredProjects=data.projects.filter(p=>{const c=data.clients.find(x=>x.id===p.clientId);return (p.name+' '+(c?.name||'')+' '+p.vertical).toLowerCase().includes(search.toLowerCase())});
 return <div className="shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">31</div><div><b>31G</b><span>Digital Operations</span></div></div><nav>{nav.map(([x,I])=><button className={section===x?'nav active':'nav'} key={x} onClick={()=>{setSection(x);setMenu(false)}}><I size={17}/><span>{x}</span></button>)}</nav><div className="tagline">Strategy<br/>Content<br/>Growth<br/>Performance</div></aside>
  <main><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}><Menu/></button><div><h1>31G Operations Management</h1><p>Clients <i>•</i> Projects <i>•</i> Workload <i>•</i> Performance</p></div><div className="date"><CalendarDays size={15}/> Sep 14, 2026 – Sep 20, 2026 <span>⌄</span></div><div className="live"><span/> Live Data<small>Operations view</small></div><button className="nav" style={{marginLeft:12}} onClick={()=>signOut({callbackUrl:'/login'})} title={data.currentUser?`Signed in as ${data.currentUser.name}`:''}><LogOut size={16}/><span>{data.currentUser?.name?.split(' ')[0]||'Sign out'}</span></button></header>
  {section==='Overview'&&<Overview data={data} selected={selected} setSelected={setSelected} selectedMember={selectedMember}/>} 
  {section==='Clients'&&<Clients data={data} search={search} setSearch={setSearch} onAdd={()=>setShowForm(true)}/>} 
  {section==='Projects'&&<Projects data={data} search={search} setSearch={setSearch} onAdd={()=>setShowForm(true)}/>} 
  {section==='Verticals'&&<Verticals data={data}/>} 
  {section==='Tasks'&&<Tasks data={data} onAdd={()=>setShowForm(true)}/>} 
  {section==='Team'&&<Team data={data} selected={selected} setSelected={setSelected}/>} 
  {section==='Proposals'&&<Proposals data={data} onAdd={()=>setShowForm(true)}/>} 
  {section==='Reports'&&<Reports data={data}/>} 
  {section==='Settings'&&<SettingsView/>}
  {showForm&&<QuickForm section={section} data={data} onClose={()=>setShowForm(false)} onSaved={()=>{setShowForm(false);load()}}/>}
 </main></div>
}
function Overview({data,selected,setSelected,selectedMember}:{data:Data;selected:string|null;setSelected:(n:string|null)=>void;selectedMember:any}){
 const chartData=data.verticals.map((v:any,i:number)=>({name:v.short,score:v.score,assigned:v.assigned,completed:v.completed,fill:colors[i]}));
 const daily=data.dailyLabels.map((d,i)=>({day:d,assigned:data.team.reduce((s,t)=>s+t.daily[i],0),completed:Math.round(data.team.reduce((s,t)=>s+t.daily[i],0)*.88)}));
 return <>
  <section className="kpis">{[['Active Clients',data.summary.clients,'Portfolios',Users],['Active Projects',data.summary.activeProjects,'Across all verticals',BriefcaseBusiness],['Open Proposals',data.summary.proposals,'Pipeline opportunities',FileText],['Team Members',data.summary.team,'Active delivery team',Users],['Tasks This Week',data.summary.totalAssigned,'Assigned workload',ListTodo],['Overall Performance',data.summary.overall+'%','Portfolio health',TrendingUp]].map(([a,b,c,I],i)=><div className={'kpi k'+i} key={a as string}><div className="icon"><I size={20}/></div><div><span>{a as string}</span><strong>{b as string}</strong><em>{c as string}</em></div></div>)}</section>
  <section className="topgrid"><Card title="Performance by Vertical" sub="Delivery score across the complete service portfolio"><ResponsiveContainer width="100%" height={250}><BarChart data={chartData}><CartesianGrid vertical={false} stroke="#e5e7eb"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="score" radius={[5,5,0,0]}>{chartData.map((e:any,i:number)=><Cell key={i} fill={e.fill}/>)}</Bar></BarChart></ResponsiveContainer></Card>
   <Card title="Portfolio Mix" sub="Vertical contribution"><div className="donut"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={data.verticals.map((v:any)=>({name:v.name,value:v.score}))} dataKey="value" innerRadius={58} outerRadius={90} paddingAngle={2}>{data.verticals.map((_:any,i:number)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{data.verticals.map((v:any,i:number)=><div key={v.name}><span style={{background:colors[i]}}/>{v.name}<b>{v.score}%</b></div>)}</div></div></Card>
   <Card title="Team Command KPIs" sub="Current delivery health"><div className="miniKpis"><Mini label="Tasks Completed" value={data.summary.totalCompleted.toString()} icon={CheckCircle2}/><Mini label="On-time Delivery" value={data.summary.onTime+'%'} icon={Clock}/><Mini label="Avg. Quality" value={data.summary.quality+'/5'} icon={Target}/><Mini label="At-risk Clients" value={data.clients.filter(c=>c.status==='At Risk').length.toString()} icon={AlertTriangle}/></div><h3 className="sectionTitle">Daily Team Workload</h3><ResponsiveContainer width="100%" height={210}><BarChart data={daily}><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="day" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="assigned" fill="#2563eb" radius={[4,4,0,0]}/><Bar dataKey="completed" fill="#10b981" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></Card>
  </section>
  <section className="middle"><Card title="Client Portfolio" sub="Health, workload and outcomes"><table><thead><tr><th>Client</th><th>Status</th><th>Verticals</th><th>Projects</th><th>Leads</th><th>Conversions</th><th>Score</th></tr></thead><tbody>{data.clients.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td><span className={'status '+c.status.toLowerCase().replace(' ','-')}>{c.status}</span></td><td><span className="pill">{c.verticals.join(', ')}</span></td><td>{data.projects.filter(p=>p.clientId===c.id).length}</td><td>{c.leads.toLocaleString()}</td><td>{c.conversions}</td><td><div className="score"><b>{c.score}%</b><span><i style={{width:c.score+'%'}}/></span></div></td></tr>)}</tbody></table></Card>
   <Card title="Weekly Performance by Vertical" sub="Assigned → completed → quality"><table className="compact"><thead><tr><th>Vertical</th><th>Assigned</th><th>Done</th><th>On-time</th><th>Quality</th></tr></thead><tbody>{data.verticals.map(v=><tr key={v.id}><td><b>{v.short}</b></td><td>{v.assigned}</td><td>{v.completed}</td><td className="green">{v.onTime}%</td><td>{v.quality}</td></tr>)}</tbody></table></Card></section>
  <section className="bottom"><Card title="Individual Team Workload" sub="Daily workload and KPI — select a member"><div className="members">{data.team.map(m=><button className={'member '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><div className="avatar">{m.name.split(' ').map((x:string)=>x[0]).join('')}</div><b>{m.name}</b><span>{m.role}</span><strong>{m.score}%</strong><small>{m.completed} done · {m.onTime}% on-time</small></button>)}</div><div className="individualGrid">{data.team.map(m=><div className="work" key={m.id}><div className="workHead"><b>{m.name}</b><span>{m.projects} projects</span></div><div className="bars">{m.daily.map((n:number,i:number)=><div key={i}><span style={{height:(n*9)+'%'}}/><small>{data.dailyLabels[i]}</small></div>)}</div><div className="workFoot"><span>{m.completed} tasks</span><b>{m.score}% KPI</b></div></div>)}</div></Card><Card title="Selected Member KPI" sub={selectedMember?selectedMember.name:'Select a member'}>{selectedMember?<div className="focus"><div className="focusTitle"><div className="avatar big">{selectedMember.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><h3>{selectedMember.name}</h3><span>{selectedMember.role}</span></div><b>{selectedMember.score}%</b></div><div className="four"><Metric l="Projects" v={selectedMember.projects}/><Metric l="Tasks Completed" v={selectedMember.completed}/><Metric l="On-time" v={selectedMember.onTime+'%'}/><Metric l="Quality" v={selectedMember.quality+'%'}/></div><div className="chips">{selectedMember.verticals.map((v:string)=><span key={v}>{v}</span>)}</div><div className="weekline"><span>Weekly KPI score</span><div><i style={{width:selectedMember.score+'%'}}/></div></div></div>:<div className="empty">Choose a team member to inspect individual KPIs and daily workload.</div>}</Card></section>
 </>
}
function Clients({data,search,setSearch,onAdd}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void}){return <PageHead title="Client Management" sub="Manage client portfolios, service verticals and account health" onAdd={onAdd} add="New Client"><SearchTable value={search} setValue={setSearch} placeholder="Search clients..."/><Card title="Client Portfolio"><table><thead><tr><th>Client</th><th>Status</th><th>Verticals</th><th>Campaigns</th><th>Reach</th><th>Engagement</th><th>Leads</th><th>Score</th></tr></thead><tbody>{data.clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td><span className={'status '+c.status.toLowerCase().replace(' ','-')}>{c.status}</span></td><td>{c.verticals.join(', ')}</td><td>{c.campaigns}</td><td>{c.reach}</td><td className="green">{c.engagement}</td><td>{c.leads.toLocaleString()}</td><td>{c.score}%</td></tr>)}</tbody></table></Card></PageHead>}
function Projects({data,search,setSearch,onAdd}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void}){return <PageHead title="Project Management" sub="Track every client project, owner, vertical, progress and deadline" onAdd={onAdd} add="New Project"><SearchTable value={search} setValue={setSearch} placeholder="Search projects, clients or verticals..."/><Card title="Project Register"><table><thead><tr><th>Project</th><th>Client</th><th>Vertical</th><th>Owner</th><th>Status</th><th>Progress</th><th>Tasks</th><th>Due</th><th>Priority</th></tr></thead><tbody>{data.projects.filter(p=>(p.name+' '+data.clients.find(c=>c.id===p.clientId)?.name+' '+p.vertical).toLowerCase().includes(search.toLowerCase())).map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{data.clients.find(c=>c.id===p.clientId)?.name}</td><td>{p.vertical}</td><td>{data.team.find(t=>t.id===p.ownerId)?.name}</td><td><span className="status">{p.status}</span></td><td><div className="score"><b>{p.progress}%</b><span><i style={{width:p.progress+'%'}}/></span></div></td><td>{p.completedTasks}/{p.tasks}</td><td>{p.due}</td><td><span className={'priority '+p.priority.toLowerCase()}>{p.priority}</span></td></tr>)}</tbody></table></Card></PageHead>}
function Verticals({data}:{data:Data}){return <PageHead title="Vertical Performance" sub="Manage the complete 31G service portfolio"><div className="verticalCards large">{data.verticals.map((v,i)=><div className="vcard" key={v.id}><div><span style={{color:colors[i]}}>●</span>{v.name}</div><strong>{v.score}%</strong><em>↑ {v.trend}% this period</em><hr/><small>{v.completed}/{v.assigned} tasks completed · {v.onTime}% on-time · {v.quality}/5 quality</small></div>)}</div></PageHead>}
function Tasks({data,onAdd}:{data:Data;onAdd:()=>void}){return <PageHead title="Task & Workload Management" sub="Assign work, monitor status and protect delivery deadlines" onAdd={onAdd} add="New Task"><div className="taskStats"><Mini label="Total Tasks" value={data.tasks.length.toString()} icon={ListTodo}/><Mini label="In Progress" value={data.tasks.filter(t=>t.status==='In Progress').length.toString()} icon={Activity}/><Mini label="Review" value={data.tasks.filter(t=>t.status==='Review').length.toString()} icon={Clock}/><Mini label="Done" value={data.tasks.filter(t=>t.status==='Done').length.toString()} icon={CheckCircle2}/></div><Card title="Task Register"><table><thead><tr><th>Task</th><th>Client</th><th>Vertical</th><th>Assignee</th><th>Status</th><th>Due</th><th>Priority</th><th>Hours</th></tr></thead><tbody>{data.tasks.map(t=><tr key={t.id}><td><b>{t.title}</b></td><td>{data.clients.find(c=>c.id===t.clientId)?.name}</td><td>{t.vertical}</td><td>{data.team.find(m=>m.id===t.assigneeId)?.name}</td><td><span className="status">{t.status}</span></td><td>{t.due}</td><td><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span></td><td>{t.estimated}</td></tr>)}</tbody></table></Card></PageHead>}
function Team({data,selected,setSelected}:{data:Data;selected:string|null;setSelected:(n:string|null)=>void}){return <PageHead title="Team Performance & Capacity" sub="Individual KPIs, daily workload and weekly performance"><div className="teamGrid">{data.team.map(m=><button className={'teamCard '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><div className="teamTop"><div className="avatar big">{m.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><h3>{m.name}</h3><span>{m.role}</span></div><strong>{m.score}%</strong></div><div className="teamMetrics"><Metric l="Projects" v={m.projects}/><Metric l="Completed" v={m.completed}/><Metric l="On-time" v={m.onTime+'%'}/><Metric l="Quality" v={m.quality+'%'}/></div><div className="bars teamBars">{m.daily.map((n:number,i:number)=><div key={i}><span style={{height:(n*10)+'%'}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></button>)}</div></PageHead>}
function Proposals({data,onAdd}:{data:Data;onAdd:()=>void}){const total=data.proposals.reduce((s,p)=>s+p.value,0);return <PageHead title="Proposal Pipeline" sub="Track new business from draft to won" onAdd={onAdd} add="New Proposal"><div className="pipeline"><Mini label="Open Proposals" value={data.proposals.length.toString()} icon={FileText}/><Mini label="Pipeline Value" value={'$'+total.toLocaleString()} icon={TrendingUp}/><Mini label="In Review" value={data.proposals.filter(p=>p.status==='In Review').length.toString()} icon={Clock}/><Mini label="Won" value={data.proposals.filter(p=>p.status==='Won').length.toString()} icon={CheckCircle2}/></div><Card title="Proposal Register"><table><thead><tr><th>Client</th><th>Service</th><th>Status</th><th>Value</th><th>Next Action</th></tr></thead><tbody>{data.proposals.map(p=><tr key={p.id}><td><b>{p.client}</b></td><td>{p.service}</td><td><span className="status">{p.status}</span></td><td>${p.value.toLocaleString()}</td><td>{p.next}</td></tr>)}</tbody></table></Card></PageHead>}
function Reports({data}:{data:Data}){const trend=data.verticals.map((v:any,i:number)=>({name:v.short,score:v.score,trend:v.trend+i/2}));return <PageHead title="Management Reports" sub="Executive view of operational performance"><section className="reportGrid"><Card title="Vertical KPI Trend"><ResponsiveContainer width="100%" height={300}><LineChart data={trend}><CartesianGrid vertical={false} stroke="#e5e7eb"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="score" stroke="#2563eb" strokeWidth={3}/></LineChart></ResponsiveContainer></Card><Card title="Management Alerts"><div className="alerts"><div><AlertTriangle/><b>{data.clients.filter(c=>c.status==='At Risk').length} clients need attention</b><span>Review Luxe Homes and TravelVista.</span></div><div><Clock/><b>{data.tasks.filter(t=>t.status!=='Done').length} open tasks</b><span>Prioritize high-impact work before due dates.</span></div><div><TrendingUp/><b>{data.summary.overall}% overall health</b><span>Portfolio is trending positively.</span></div></div></Card></section></PageHead>}
function SettingsView(){return <PageHead title="System Settings" sub="Configure the 31G operations workspace"><div className="settings"><div><b>Company</b><span>31G</span></div><div><b>Workspace</b><span>Digital Marketing Operations</span></div><div><b>Performance cadence</b><span>Weekly with daily workload monitoring</span></div><div><b>Tracked verticals</b><span>10 service verticals</span></div></div></PageHead>}
function PageHead({title,sub,onAdd,add,children}:{title:string;sub:string;onAdd?:()=>void;add?:string;children:React.ReactNode}){return <><div className="pageHead"><div><h2>{title}</h2><p>{sub}</p></div>{onAdd&&<button className="primary" onClick={onAdd}><Plus size={15}/>{add}</button>}</div>{children}</>}
function SearchTable({value,setValue,placeholder}:{value:string;setValue:(s:string)=>void;placeholder:string}){return <div className="searchbar"><Search size={16}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>setValue('')}><X size={14}/></button>}</div>}
function Card({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <div className="card"><div className="cardHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div><ChevronRight size={16} className="chev"/></div>{children}</div>}
function Mini({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="mini"><Icon size={18}/><span>{label}</span><b>{value}</b></div>}
function Metric({l,v}:{l:string;v:string|number}){return <div><span>{l}</span><b>{v}</b></div>}
function QuickForm({section,data,onClose,onSaved}:{section:string;data:Data|null;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const endpoint=section==='Clients'?'clients':section==='Projects'?'projects':section==='Tasks'?'tasks':'proposals';
  const firstClientId=data?.clients?.[0]?.id;
  const firstProjectId=data?.projects?.[0]?.id;
  const firstTeamId=data?.team?.[0]?.id;
  const submit=async()=>{
    if((endpoint==='projects'&&!firstClientId)||(endpoint==='tasks'&&!firstProjectId)){setError('Add a client/project first.');return}
    setBusy(true);setError('');
    const body=endpoint==='clients'?{name:name||'New Client',verticals:['SEO'],campaigns:0,reach:'0',engagement:'0%',leads:0,conversions:0,score:0,status:'Active'}
      :endpoint==='projects'?{name:name||'New Project',clientId:firstClientId,ownerId:firstTeamId,status:'Planning',due:'2026-10-01',priority:'Medium'}
      :endpoint==='tasks'?{title:name||'New Task',projectId:firstProjectId,clientId:firstClientId,assigneeId:firstTeamId,due:'2026-09-30',status:'Todo',priority:'Medium',estimated:1}
      :{client:name||'New Client',service:'SEO',status:'Draft',value:0,next:'Define next action'};
    const res=await fetch('/api/'+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    setBusy(false);
    if(!res.ok){setError('Could not save — check permissions.');return}
    onSaved();
  };
  return <div className="modal"><div className="modalBox"><div className="modalHead"><div><h2>Add {section==='Clients'?'Client':section==='Projects'?'Project':section==='Tasks'?'Task':'Proposal'}</h2><p>Create a new record in the operations system.</p></div><button onClick={onClose}><X/></button></div><label>Name / Title<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter name..."/></label>{error&&<p style={{color:'#dc2626',fontSize:13}}>{error}</p>}<div className="modalActions"><button onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={submit}>{busy?'Saving...':'Create Record'}</button></div></div></div>}
