'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Activity,BarChart3,BriefcaseBusiness,CalendarDays,CheckCircle2,ClipboardList,Clock,FileText,Home,Menu,Plus,Search,Settings,Target,TrendingUp,Users,Layers3,ListTodo,ChevronRight,X,AlertTriangle,LogOut} from 'lucide-react';
import {signOut} from 'next-auth/react';

type Data={clients:any[];team:any[];verticals:any[];proposals:any[];projects:any[];tasks:any[];dailyLabels:string[];summary:any;currentUser?:{id:string;name:string;role:'ADMIN'|'MEMBER';avatarUrl?:string|null}};
const colors=['#2563eb','#10b981','#8b5cf6','#f59e0b','#ec4899','#06b6d4','#64748b','#f97316','#6366f1','#14b8a6'];
const nav=[['Overview',Home],['Clients',Users],['Projects',BriefcaseBusiness],['Verticals',Layers3],['Tasks',ListTodo],['Team',Users],['Proposals',FileText],['Reports',ClipboardList],['Settings',Settings]] as const;
export default function Dashboard(){
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [section,setSection]=useState('Overview'); const [selected,setSelected]=useState<string|null>(null); const [menu,setMenu]=useState(false); const [search,setSearch]=useState(''); const [formState,setFormState]=useState<{section:string;record?:any}|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/dashboard');const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to load dashboard data.');setData(payload)}catch(error){setData(null);setError(error instanceof Error?error.message:'Unable to load dashboard data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading) return <div className="loading">Loading 31G Operations Center…</div>;
 if(error) return <div className="loading">{error}</div>;
 if(!data) return <div className="loading">No dashboard data available.</div>;
 const selectedMember=data.team.find(t=>t.id===selected);
 const filteredClients=data.clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase()));
 const filteredProjects=data.projects.filter(p=>{const c=data.clients.find(x=>x.id===p.clientId);return (p.name+' '+(c?.name||'')+' '+p.vertical).toLowerCase().includes(search.toLowerCase())});
 return <div className="shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">31</div><div><b>31G</b><span>Digital Operations</span></div></div><nav>{nav.map(([x,I])=><button className={section===x?'nav active':'nav'} key={x} onClick={()=>{setSection(x);setMenu(false)}}><I size={17}/><span>{x}</span></button>)}</nav><div className="tagline">Strategy<br/>Content<br/>Growth<br/>Performance</div></aside>
  <main><header><button className="mobileMenu" onClick={()=>setMenu(!menu)}><Menu/></button><div><h1>31G Operations Management</h1><p>Clients <i>•</i> Projects <i>•</i> Workload <i>•</i> Performance</p></div><div className="date"><CalendarDays size={15}/> Sep 14, 2026 – Sep 20, 2026 <span>⌄</span></div><div className="live"><span/> Live Data<small>Operations view</small></div><button className="nav" style={{marginLeft:12}} onClick={()=>signOut({callbackUrl:'/login'})} title={data.currentUser?`Signed in as ${data.currentUser.name}`:''}><LogOut size={16}/><span>{data.currentUser?.name?.split(' ')[0]||'Sign out'}</span></button></header>
  {section==='Overview'&&<Overview data={data} selected={selected} setSelected={setSelected} selectedMember={selectedMember}/>}
  {section==='Clients'&&<ManagedClients data={data} search={search} setSearch={setSearch} onAdd={()=>setFormState({section:'Clients'})} onEdit={record=>setFormState({section:'Clients',record})} onDelete={id=>removeRecord('clients',id,load)}/>}
  {section==='Projects'&&<ManagedProjects data={data} search={search} setSearch={setSearch} onAdd={()=>setFormState({section:'Projects'})} onEdit={record=>setFormState({section:'Projects',record})} onDelete={id=>removeRecord('projects',id,load)}/>}
  {section==='Verticals'&&<Verticals data={data}/>}
  {section==='Tasks'&&<ManagedTasks data={data} onAdd={()=>setFormState({section:'Tasks'})} onEdit={record=>setFormState({section:'Tasks',record})} onDelete={id=>removeRecord('tasks',id,load)}/>}
  {section==='Team'&&<ManagedTeam data={data} selected={selected} setSelected={setSelected} onAdd={()=>setFormState({section:'Team'})} onEdit={record=>setFormState({section:'Team',record})} onDelete={id=>removeRecord('team',id,load)}/>}
  {section==='Proposals'&&<ManagedProposals data={data} onAdd={()=>setFormState({section:'Proposals'})} onEdit={record=>setFormState({section:'Proposals',record})} onDelete={id=>removeRecord('proposals',id,load)}/>}
  {section==='Reports'&&<Reports data={data}/>}
  {section==='Settings'&&<SettingsView data={data}/>}
  {formState&&<QuickForm section={formState.section} data={data} record={formState.record} onClose={()=>setFormState(null)} onSaved={()=>{setFormState(null);load()}}/>}
 </main></div>
}
async function removeRecord(endpoint:string,id:string,refresh:()=>void){
 if(!window.confirm('Delete this record? This cannot be undone.')) return;
 const response=await fetch(`/api/${endpoint}/${id}`,{method:'DELETE'});
 if(!response.ok){window.alert('You do not have permission to delete this record.');return}
 refresh();
}
function ManagedProjects({data,search,setSearch,onAdd,onEdit,onDelete}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void;onEdit:(record:any)=>void;onDelete:(id:string)=>void}){
 const projects=data.projects.filter(p=>(p.name+' '+(data.clients.find(c=>c.id===p.clientId)?.name||'')+' '+p.vertical).toLowerCase().includes(search.toLowerCase()));
 return <PageHead title="Project Management" sub="View, edit and remove projects" onAdd={onAdd} add="New Project"><SearchTable value={search} setValue={setSearch} placeholder="Search projects..."/><Card title="Project Register"><table><thead><tr><th>Project</th><th>Client</th><th>Owner</th><th>Status</th><th>Due</th><th>Priority</th><th>Actions</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{data.clients.find(c=>c.id===p.clientId)?.name}</td><td>{data.team.find(t=>t.id===p.ownerId)?.name||'Unassigned'}</td><td><span className="status">{p.status}</span></td><td>{p.due||'—'}</td><td><span className={'priority '+p.priority.toLowerCase()}>{p.priority}</span></td><td><button className="tableAction" onClick={()=>onEdit(p)}>Edit</button>{data.currentUser?.role==='ADMIN'&&<button className="tableAction danger" onClick={()=>onDelete(p.id)}>Delete</button>}</td></tr>)}</tbody></table></Card></PageHead>
}
function ManagedClients({data,search,setSearch,onAdd,onEdit,onDelete}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void;onEdit:(record:any)=>void;onDelete:(id:string)=>void}){
 const clients=data.clients.filter(client=>client.name.toLowerCase().includes(search.toLowerCase()));
 return <PageHead title="Client Management" sub="View, edit and remove client portfolios" onAdd={onAdd} add="New Client"><SearchTable value={search} setValue={setSearch} placeholder="Search clients..."/><Card title="Client Portfolio"><table><thead><tr><th>Client</th><th>Status</th><th>Verticals</th><th>Projects</th><th>Score</th><th>Actions</th></tr></thead><tbody>{clients.map(client=><tr key={client.id}><td><b>{client.name}</b></td><td><span className="status">{client.status}</span></td><td>{client.verticals.join(', ')}</td><td>{data.projects.filter(project=>project.clientId===client.id).length}</td><td>{client.score}%</td><td><button className="tableAction" onClick={()=>onEdit(client)}>Edit</button>{data.currentUser?.role==='ADMIN'&&<button className="tableAction danger" onClick={()=>onDelete(client.id)}>Delete</button>}</td></tr>)}</tbody></table></Card></PageHead>
}
function ManagedProposals({data,onAdd,onEdit,onDelete}:{data:Data;onAdd:()=>void;onEdit:(record:any)=>void;onDelete:(id:string)=>void}){
 return <PageHead title="Proposal Pipeline" sub="View, edit and remove business proposals" onAdd={onAdd} add="New Proposal"><Card title="Proposal Register"><table><thead><tr><th>Client</th><th>Service</th><th>Status</th><th>Value</th><th>Next Action</th><th>Actions</th></tr></thead><tbody>{data.proposals.map(proposal=><tr key={proposal.id}><td><b>{proposal.client}</b></td><td>{proposal.service}</td><td><span className="status">{proposal.status}</span></td><td>${proposal.value.toLocaleString()}</td><td>{proposal.next}</td><td><button className="tableAction" onClick={()=>onEdit(proposal)}>Edit</button>{data.currentUser?.role==='ADMIN'&&<button className="tableAction danger" onClick={()=>onDelete(proposal.id)}>Delete</button>}</td></tr>)}</tbody></table></Card></PageHead>
}
function ManagedTasks({data,onAdd,onEdit,onDelete}:{data:Data;onAdd:()=>void;onEdit:(record:any)=>void;onDelete:(id:string)=>void}){
 return <PageHead title="Task & Workload Management" sub="View, edit, assign and remove tasks" onAdd={onAdd} add="New Task"><Card title="Task Register"><table><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Status</th><th>Due</th><th>Priority</th><th>Actions</th></tr></thead><tbody>{data.tasks.map(t=><tr key={t.id}><td><b>{t.title}</b></td><td>{data.projects.find(p=>p.id===t.projectId)?.name||'—'}</td><td>{data.team.find(m=>m.id===t.assigneeId)?.name||'Unassigned'}</td><td><span className="status">{t.status}</span></td><td>{t.due||'—'}</td><td><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span></td><td><button className="tableAction" onClick={()=>onEdit(t)}>Edit</button>{data.currentUser?.role==='ADMIN'&&<button className="tableAction danger" onClick={()=>onDelete(t.id)}>Delete</button>}</td></tr>)}</tbody></table></Card></PageHead>
}
function ManagedTeam({data,selected,setSelected,onAdd,onEdit,onDelete}:{data:Data;selected:string|null;setSelected:(n:string|null)=>void;onAdd:()=>void;onEdit:(record:any)=>void;onDelete:(id:string)=>void}){
 return <PageHead title="Team Performance & Capacity" sub="View, manage and deactivate team accounts" onAdd={data.currentUser?.role==='ADMIN'?onAdd:undefined} add="Add Member"><div className="teamGrid">{data.team.map(m=><div className={'teamCard '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><div className="teamTop"><div className="avatar big">{m.avatarUrl?<img src={m.avatarUrl} alt=""/>:m.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><h3>{m.name}</h3><span>{m.role}</span></div><strong>{m.score}%</strong></div><div className="teamMetrics"><Metric l="Projects" v={m.projects}/><Metric l="Completed" v={m.completed}/><Metric l="On-time" v={m.onTime+'%'}/><Metric l="Quality" v={m.quality+'%'}/></div>{data.currentUser?.role==='ADMIN'&&<div className="rowActions"><button className="tableAction" onClick={e=>{e.stopPropagation();onEdit(m)}}>Edit</button><button className="tableAction danger" onClick={e=>{e.stopPropagation();onDelete(m.id)}}>Deactivate</button></div>}</div>)}</div></PageHead>
}
function Overview({data,selected,setSelected,selectedMember}:{data:Data;selected:string|null;setSelected:(n:string|null)=>void;selectedMember:any}){
 const chartData=data.verticals.map((v:any,i:number)=>({name:v.short,score:v.score,assigned:v.assigned,completed:v.completed,fill:colors[i]}));
 const daily=data.dailyLabels.map((d,i)=>({day:d,assigned:data.team.reduce((s,t)=>s+t.daily[i],0),completed:Math.round(data.team.reduce((s,t)=>s+t.daily[i],0)*.88)}));
 return <>
  <section className="kpis">{[['Active Clients',data.summary.clients,'Portfolios',Users],['Active Projects',data.summary.activeProjects,'Across all verticals',BriefcaseBusiness],['Open Proposals',data.summary.proposals,'Pipeline opportunities',FileText],['Team Members',data.summary.team,'Active delivery team',Users],['Tasks This Week',data.summary.totalAssigned,'Assigned workload',ListTodo],['Overall Performance',data.summary.overall+'%','Portfolio health',TrendingUp]].map(([a,b,c,I],i)=><div className={'kpi k'+i} key={a as string}><div className="icon"><I size={20}/></div><div><span>{a as string}</span><strong>{b as string}</strong><em>{c as string}</em></div></div>)}</section>
  <section className="topgrid"><Card title="Performance by Vertical" sub="Delivery score across the complete service portfolio"><ResponsiveContainer width="100%" height={250}><BarChart data={chartData}><CartesianGrid vertical={false} stroke="#e5e7eb"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis domain={[0,100]} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="score" radius={[5,5,0,0]}>{chartData.map((e:any,i:number)=><Cell key={i} fill={e.fill}/>)}</Bar></BarChart></ResponsiveContainer></Card>
   <Card title="Portfolio Mix" sub="Vertical contribution"><div className="donut"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={data.verticals.map((v:any)=>({name:v.name,value:v.score}))} dataKey="value" innerRadius={58} outerRadius={90} paddingAngle={2}>{data.verticals.map((_:any,i:number)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{data.verticals.map((v:any,i:number)=><div key={v.name}><span style={{background:colors[i]}}/>{v.name}<b>{v.score}%</b></div>)}</div></div></Card>
   <Card title="Team Command KPIs" sub="Current delivery health"><div className="miniKpis"><Mini label="Tasks Completed" value={data.summary.totalCompleted.toString()} icon={CheckCircle2}/><Mini label="On-time Delivery" value={data.summary.onTime+'%'} icon={Clock}/><Mini label="Avg. Quality" value={data.summary.quality+'/5'} icon={Target}/><Mini label="At-risk Clients" value={data.clients.filter(c=>c.status==='At Risk').length.toString()} icon={AlertTriangle}/></div><h3 className="sectionTitle">Daily Team Workload</h3><ResponsiveContainer width="100%" height={210}><BarChart data={daily}><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="day" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="assigned" fill="#2563eb" radius={[4,4,0,0]}/><Bar dataKey="completed" fill="#10b981" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></Card>
  </section>
  <section className="middle"><Card title="Client Portfolio" sub="Health, workload and outcomes"><table><thead><tr><th>Client</th><th>Status</th><th>Verticals</th><th>Projects</th><th>Leads</th><th>Conversions</th><th>Score</th></tr></thead><tbody>{data.clients.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td><span className={'status '+c.status.toLowerCase().replace(' ','-')}>{c.status}</span></td><td><span className="pill">{c.verticals.join(', ')}</span></td><td>{data.projects.filter(p=>p.clientId===c.id).length}</td><td>{c.leads.toLocaleString()}</td><td>{c.conversions}</td><td><div className="score"><b>{c.score}%</b><span><i style={{width:c.score+'%'}}/></span></div></td></tr>)}</tbody></table></Card>
   <Card title="Weekly Performance by Vertical" sub="Assigned → completed → quality"><table className="compact"><thead><tr><th>Vertical</th><th>Assigned</th><th>Done</th><th>On-time</th><th>Quality</th></tr></thead><tbody>{data.verticals.map(v=><tr key={v.id}><td><b>{v.short}</b></td><td>{v.assigned}</td><td>{v.completed}</td><td className="green">{v.onTime}%</td><td>{v.quality}</td></tr>)}</tbody></table></Card></section>
  <section className="bottom"><Card title="Individual Team Workload" sub="Daily workload and KPI — select a member"><div className="members">{data.team.map(m=><button className={'member '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><div className="avatar">{m.name.split(' ').map((x:string)=>x[0]).join('')}</div><b>{m.name}</b><span>{m.role}</span><strong>{m.score}%</strong><small>{m.completed} done · {m.onTime}% on-time</small></button>)}</div><div className="individualGrid">{data.team.map(m=><div className="work" key={m.id}><div className="workHead"><b>{m.name}</b><span>{m.projects} projects</span></div><div className="bars">{m.daily.map((n:number,i:number)=><div key={i}><span style={{height:(n*9)+'%'}}/><small>{data.dailyLabels[i]}</small></div>)}</div><div className="workFoot"><span>{m.completed} tasks</span><b>{m.score}% KPI</b></div></div>)}</div></Card><Card title="Selected Member KPI" sub={selectedMember?selectedMember.name:'Select a member'}>{selectedMember?<div className="focus"><div className="focusTitle"><div className="avatar big">{selectedMember.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><h3>{selectedMember.name}</h3><span>{selectedMember.role}</span></div><b>{selectedMember.score}%</b></div><div className="four"><Metric l="Projects" v={selectedMember.projects}/><Metric l="Tasks Completed" v={selectedMember.completed}/><Metric l="On-time" v={selectedMember.onTime+'%'}/><Metric l="Quality" v={selectedMember.quality+'%'}/></div><div className="chips">{selectedMember.verticals.map((v:string)=><span key={v}>{v}</span>)}</div><div className="weekline"><span>Weekly KPI score</span><div><i style={{width:selectedMember.score+'%'}}/></div></div></div>:<div className="empty">Choose a team member to inspect individual KPIs and daily workload.</div>}</Card></section>
 </>
}
function Clients({data,search,setSearch,onAdd}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void}){return <PageHead title="Client Management" sub="Manage client portfolios, service verticals and account health" onAdd={onAdd} add="New Client"><SearchTable value={search} setValue={setSearch} placeholder="Search clients..."/><Card title="Client Portfolio"><table><thead><tr><th>Client</th><th>Status</th><th>Verticals</th><th>Campaigns</th><th>Reach</th><th>Engagement</th><th>Leads</th><th>Score</th></tr></thead><tbody>{data.clients.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td><span className={'status '+c.status.toLowerCase().replace(' ','-')}>{c.status}</span></td><td>{c.verticals.join(', ')}</td><td>{c.campaigns}</td><td>{c.reach}</td><td className="green">{c.engagement}</td><td>{c.leads.toLocaleString()}</td><td>{c.score}%</td></tr>)}</tbody></table></Card></PageHead>}
function Projects({data,search,setSearch,onAdd}:{data:Data;search:string;setSearch:(s:string)=>void;onAdd:()=>void}){return <PageHead title="Project Management" sub="Track every client project, owner, vertical, progress and deadline" onAdd={onAdd} add="New Project"><SearchTable value={search} setValue={setSearch} placeholder="Search projects, clients or verticals..."/><Card title="Project Register"><table><thead><tr><th>Project</th><th>Client</th><th>Vertical</th><th>Owner</th><th>Status</th><th>Progress</th><th>Tasks</th><th>Due</th><th>Priority</th></tr></thead><tbody>{data.projects.filter(p=>(p.name+' '+data.clients.find(c=>c.id===p.clientId)?.name+' '+p.vertical).toLowerCase().includes(search.toLowerCase())).map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{data.clients.find(c=>c.id===p.clientId)?.name}</td><td>{p.vertical}</td><td>{data.team.find(t=>t.id===p.ownerId)?.name}</td><td><span className="status">{p.status}</span></td><td><div className="score"><b>{p.progress}%</b><span><i style={{width:p.progress+'%'}}/></span></div></td><td>{p.completedTasks}/{p.tasks}</td><td>{p.due}</td><td><span className={'priority '+p.priority.toLowerCase()}>{p.priority}</span></td></tr>)}</tbody></table></Card></PageHead>}
function Verticals({data}:{data:Data}){return <PageHead title="Vertical Performance" sub="Manage the complete 31G service portfolio"><div className="verticalCards large">{data.verticals.map((v,i)=><div className="vcard" key={v.id}><div><span style={{color:colors[i]}}>●</span>{v.name}</div><strong>{v.score}%</strong><em>↑ {v.trend}% this period</em><hr/><small>{v.completed}/{v.assigned} tasks completed · {v.onTime}% on-time · {v.quality}/5 quality</small></div>)}</div></PageHead>}
function Tasks({data,onAdd}:{data:Data;onAdd:()=>void}){return <PageHead title="Task & Workload Management" sub="Assign work, monitor status and protect delivery deadlines" onAdd={onAdd} add="New Task"><div className="taskStats"><Mini label="Total Tasks" value={data.tasks.length.toString()} icon={ListTodo}/><Mini label="In Progress" value={data.tasks.filter(t=>t.status==='In Progress').length.toString()} icon={Activity}/><Mini label="Review" value={data.tasks.filter(t=>t.status==='Review').length.toString()} icon={Clock}/><Mini label="Done" value={data.tasks.filter(t=>t.status==='Done').length.toString()} icon={CheckCircle2}/></div><Card title="Task Register"><table><thead><tr><th>Task</th><th>Client</th><th>Vertical</th><th>Assignee</th><th>Status</th><th>Due</th><th>Priority</th><th>Hours</th></tr></thead><tbody>{data.tasks.map(t=><tr key={t.id}><td><b>{t.title}</b></td><td>{data.clients.find(c=>c.id===t.clientId)?.name}</td><td>{t.vertical}</td><td>{data.team.find(m=>m.id===t.assigneeId)?.name}</td><td><span className="status">{t.status}</span></td><td>{t.due}</td><td><span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span></td><td>{t.estimated}</td></tr>)}</tbody></table></Card></PageHead>}
function Team({data,selected,setSelected,onAdd}:{data:Data;selected:string|null;setSelected:(n:string|null)=>void;onAdd:()=>void}){return <PageHead title="Team Performance & Capacity" sub="Individual KPIs, daily workload and weekly performance" onAdd={data.currentUser?.role==='ADMIN'?onAdd:undefined} add="Add Member"><div className="teamGrid">{data.team.map(m=><button className={'teamCard '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><div className="teamTop"><div className="avatar big">{m.name.split(' ').map((x:string)=>x[0]).join('')}</div><div><h3>{m.name}</h3><span>{m.role}</span></div><strong>{m.score}%</strong></div><div className="teamMetrics"><Metric l="Projects" v={m.projects}/><Metric l="Completed" v={m.completed}/><Metric l="On-time" v={m.onTime+'%'}/><Metric l="Quality" v={m.quality+'%'}/></div><div className="bars teamBars">{m.daily.map((n:number,i:number)=><div key={i}><span style={{height:(n*10)+'%'}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></button>)}</div></PageHead>}
function Proposals({data,onAdd}:{data:Data;onAdd:()=>void}){const total=data.proposals.reduce((s,p)=>s+p.value,0);return <PageHead title="Proposal Pipeline" sub="Track new business from draft to won" onAdd={onAdd} add="New Proposal"><div className="pipeline"><Mini label="Open Proposals" value={data.proposals.length.toString()} icon={FileText}/><Mini label="Pipeline Value" value={'$'+total.toLocaleString()} icon={TrendingUp}/><Mini label="In Review" value={data.proposals.filter(p=>p.status==='In Review').length.toString()} icon={Clock}/><Mini label="Won" value={data.proposals.filter(p=>p.status==='Won').length.toString()} icon={CheckCircle2}/></div><Card title="Proposal Register"><table><thead><tr><th>Client</th><th>Service</th><th>Status</th><th>Value</th><th>Next Action</th></tr></thead><tbody>{data.proposals.map(p=><tr key={p.id}><td><b>{p.client}</b></td><td>{p.service}</td><td><span className="status">{p.status}</span></td><td>${p.value.toLocaleString()}</td><td>{p.next}</td></tr>)}</tbody></table></Card></PageHead>}
function Reports({data}:{data:Data}){const trend=data.verticals.map((v:any,i:number)=>({name:v.short,score:v.score,trend:v.trend+i/2}));return <PageHead title="Management Reports" sub="Executive view of operational performance"><section className="reportGrid"><Card title="Vertical KPI Trend"><ResponsiveContainer width="100%" height={300}><LineChart data={trend}><CartesianGrid vertical={false} stroke="#e5e7eb"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="score" stroke="#2563eb" strokeWidth={3}/></LineChart></ResponsiveContainer></Card><Card title="Management Alerts"><div className="alerts"><div><AlertTriangle/><b>{data.clients.filter(c=>c.status==='At Risk').length} clients need attention</b><span>Review Luxe Homes and TravelVista.</span></div><div><Clock/><b>{data.tasks.filter(t=>t.status!=='Done').length} open tasks</b><span>Prioritize high-impact work before due dates.</span></div><div><TrendingUp/><b>{data.summary.overall}% overall health</b><span>Portfolio is trending positively.</span></div></div></Card></section></PageHead>}
function SettingsView({data}:{data:Data}){
  const [currentPassword,setCurrentPassword]=useState('');
  const [newPassword,setNewPassword]=useState('');
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const changePassword=async()=>{
    setBusy(true);setMessage('');
    const response=await fetch('/api/account/password',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});
    const payload=await response.json();
    setBusy(false);
    if(!response.ok){setMessage(payload.error||'Could not change password.');return}
    setCurrentPassword('');setNewPassword('');setMessage('Password changed successfully.');
  };
  return <PageHead title="System Settings" sub="Configure the 31G operations workspace"><div className="settings"><div><b>Company</b><span>31G</span></div><div><b>Workspace</b><span>Digital Marketing Operations</span></div><div><b>Performance cadence</b><span>Weekly with daily workload monitoring</span></div><div><b>Tracked verticals</b><span>10 service verticals</span></div></div><ProfileSettings data={data}/><Card title="Change Password" sub="Update your own sign-in password"><div className="settingsPassword"><label>Current password<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>New password<input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label>{message&&<p>{message}</p>}<button className="primary" disabled={busy||!currentPassword||newPassword.length<8} onClick={changePassword}>{busy?'Updating...':'Change Password'}</button></div></Card></PageHead>}
function ProfileSettings({data}:{data:Data}){
 const currentMember=data.team.find(member=>member.id===data.currentUser?.id); const [name,setName]=useState(currentMember?.name||''); const [jobTitle,setJobTitle]=useState(''); const [avatarUrl,setAvatarUrl]=useState(currentMember?.avatarUrl||''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const save=async()=>{setBusy(true);setMessage('');const response=await fetch('/api/account/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,jobTitle,avatarUrl:avatarUrl||null})});const payload=await response.json();setBusy(false);setMessage(response.ok?'Profile updated.':payload.error||'Could not update profile.');if(response.ok) window.location.reload()};
 const choose=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2_000_000){setMessage('Choose an image under 2 MB.');return}const reader=new FileReader();reader.onload=()=>setAvatarUrl(String(reader.result));reader.readAsDataURL(file)};
 return <Card title="My Profile" sub="Update your name, title, and profile image"><div className="profileSettings"><div className="profilePreview">{avatarUrl?<img src={avatarUrl} alt="Profile preview"/>:<Users size={22}/>}</div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Job title<input value={jobTitle} onChange={e=>setJobTitle(e.target.value)} placeholder="Your role"/></label><label>Profile image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/></label>{message&&<p>{message}</p>}<button className="primary" disabled={busy||!name} onClick={save}>{busy?'Saving...':'Save Profile'}</button></div></Card>
}
function PageHead({title,sub,onAdd,add,children}:{title:string;sub:string;onAdd?:()=>void;add?:string;children:React.ReactNode}){return <><div className="pageHead"><div><h2>{title}</h2><p>{sub}</p></div>{onAdd&&<button className="primary" onClick={onAdd}><Plus size={15}/>{add}</button>}</div>{children}</>}
function SearchTable({value,setValue,placeholder}:{value:string;setValue:(s:string)=>void;placeholder:string}){return <div className="searchbar"><Search size={16}/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/>{value&&<button onClick={()=>setValue('')}><X size={14}/></button>}</div>}
function Card({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <div className="card"><div className="cardHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div><ChevronRight size={16} className="chev"/></div>{children}</div>}
function Mini({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="mini"><Icon size={18}/><span>{label}</span><b>{value}</b></div>}
function Metric({l,v}:{l:string;v:string|number}){return <div><span>{l}</span><b>{v}</b></div>}
function QuickForm({section,data,record,onClose,onSaved}:{section:string;data:Data|null;record?:any;onClose:()=>void;onSaved:()=>void}){
  const editing=Boolean(record);
  const [name,setName]=useState(record?.name||record?.title||'');
  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const [status,setStatus]=useState(record?.status||'Planning');
  const [priority,setPriority]=useState(record?.priority||'Medium');
  const [due,setDue]=useState(record?.due||'');
  const [assigneeId,setAssigneeId]=useState(record?.assigneeId||'');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const endpoint=section==='Team'?'team':section==='Clients'?'clients':section==='Projects'?'projects':section==='Tasks'?'tasks':'proposals';
  const firstClientId=data?.clients?.[0]?.id;
  const firstProjectId=data?.projects?.[0]?.id;
  const firstTeamId=data?.team?.[0]?.id;
  const submit=async()=>{
    if(!editing&&((endpoint==='projects'&&!firstClientId)||(endpoint==='tasks'&&!firstProjectId))){setError('Add a client/project first.');return}
    if(endpoint==='team'&&!editing&&(!email||password.length<8)){setError('Email and an 8-character password are required.');return}
    setBusy(true);setError('');
    const body=endpoint==='team'?editing?{name,jobTitle:record.role}:{name,email,password,role:'MEMBER'}:endpoint==='clients'?{name:name||'New Client',verticals:['SEO'],campaigns:0,reach:'0',engagement:'0%',leads:0,conversions:0,score:0,status:'Active'}
      :endpoint==='projects'?{name:name||'New Project',clientId:firstClientId,ownerId:firstTeamId,status,due:due||null,priority}
      :endpoint==='tasks'?{title:name||'New Task',projectId:record?.projectId||firstProjectId,clientId:record?.clientId||firstClientId,assigneeId:assigneeId||null,due:due||null,status,priority,estimated:record?.estimated||1}
      :{client:name||'New Client',service:'SEO',status:'Draft',value:0,next:'Define next action'};
    const res=await fetch(editing?`/api/${endpoint}/${record.id}`:'/api/'+endpoint,{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    setBusy(false);
    if(!res.ok){const payload=await res.json().catch(()=>null);setError(payload?.error||'Could not save — check permissions.');return}
    onSaved();
  };
  return <div className="modal"><div className="modalBox"><div className="modalHead"><div><h2>{editing?'Edit ':'Add '}{section==='Team'?'Team Member':section==='Clients'?'Client':section==='Projects'?'Project':section==='Tasks'?'Task':'Proposal'}</h2><p>{editing?'Update this record.':'Create a new record in the operations system.'}</p></div><button onClick={onClose}><X/></button></div><label>{section==='Tasks'?'Task title':'Name'}<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter name..."/></label>{(section==='Projects'||section==='Tasks')&&<><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{(section==='Projects'?['Planning','Active','Review','Completed','Blocked']:['Todo','In Progress','Review','Done']).map(value=><option key={value}>{value}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{['Low','Medium','High'].map(value=><option key={value}>{value}</option>)}</select></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></>}{section==='Tasks'&&<label>Assignee<select value={assigneeId} onChange={e=>setAssigneeId(e.target.value)}><option value="">Unassigned</option>{data?.team.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label>}{section==='Team'&&!editing&&<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="member@31g.com"/></label><label>Temporary password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label></>}{error&&<p style={{color:'#dc2626',fontSize:13}}>{error}</p>}<div className="modalActions"><button onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={submit}>{busy?'Saving...':editing?'Save Changes':'Create Record'}</button></div></div></div>}
